image: ruby:2.3.3

pages:
  script:
  - gem install jekyll
  - jekyll build -d public/
  - cp ./public/.well-known/acme-challenge/3tqqhSAqPTD9UEWg644M-GqsF2MXRFFzdd5jrzesTJI.html ./public/.well-known/acme-challenge/3tqqhSAqPTD9UEWg644M-GqsF2MXRFFzdd5jrzesTJI
  artifacts:
    paths:
    - public
  only:
  - master
