image: ruby:2.3.3

pages:
  script:
  - gem install jekyll
  - jekyll build -d public/
  - cp ./public/.well-known/acme-challenge/9FrBkdA0d8oRE24uG4fUm5BJsEXvaoHeGxPjl23Tt7o.html ./public/.well-known/acme-challenge/9FrBkdA0d8oRE24uG4fUm5BJsEXvaoHeGxPjl23Tt7o
  artifacts:
    paths:
    - public
  only:
  - master
