image: ruby:2.3.3

pages:
  script:
  - gem install jekyll
  - jekyll build -d public/
  - cp ./public/.well-known/acme-challenge/aJy1ec0ak5YjmCRhAdDdK2u6470_pE34nbkmIeea83A.html ./public/.well-known/acme-challenge/aJy1ec0ak5YjmCRhAdDdK2u6470_pE34nbkmIeea83A
  artifacts:
    paths:
    - public
  only:
  - master
