image: ruby:2.3.3

cache:
  paths:
    - vendor/


pages:
  script:
  - bundle install --path vendor
  - jekyll build -d public/
  - cd public/.well-known/acme-challenge && find -type f -name '*.html' | while read f; do mv "$f" "${f%.html}"; done
  artifacts:
    paths:
    - public
  only:
  - master
