#
###################################
# Site wide configuration
####################################
#
title: SebastianKlier.com
email:
description: Full-Stack Developer
url: https://www.sebastianklier.com


#
###################################
# Jekyll configuration
####################################
#
timezone:          Europe/Berlin
markdown:          kramdown
highlighter:       rouge
excerpt_separator: <!--more-->
#permalink:         /articles/:year-:month/:title.html
pagination:
  enabled: true
  debug: false
  collection: 'posts'
  per_page: 10
  permalink: '/blog/:num/' # Pages are index.html inside this folder (default)
  title: ':title - page :num'
  limit: 0
  sort_field: 'date'
  sort_reverse: true
  category: 'posts'
  tag: ''
  locale: ''
  trail:
    before: 2
    after: 2
  extension: html
  indexpage:

kramdown:
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  enable_coderay: false

exclude: [node_modules, vendor, "Gemfile", "Gemfile.lock", "package.json"]

#
###################################
# Site Owner configuration
####################################
#
owner:
  name: Sebastian Klier
  avatar: avatar.jpg
  job: "Founder at <a href='https://newworldfans.com' title='New World MMO'>NewWorldFans</a>, <a href='https://www.newworld-map.com' title='New World Map'>NewWorld-Map</a>."
  bio: "Full-Stack Developer with Kubernetes Experience."
  email: hello@sebastianklier.com
  disqus-shortname: sebastianklier
  twitter: sebastianklier
  facebook: #username
  google:
    plus: #username
    analytics: UA-100510828-1
    verify:
    ad-client:
    ad-slot:
  bing-verify:
  github: sekl
  gitlab: sekl
  stackoverflow: 3544233/sekl
  linkedin: sebastianklier
  skype: #username
  xing: #username
  instagram: #username
  lastfm: #username
  tumblr: #username
  pinterest: #username
  foursquare: #username
  steam: #username
  dribbble: #username
  youtube: #username
  soundcloud: #username
  weibo: #username
  flickr: #username
  500px: #username
  codepen: #username
